### ISSUE TITLE
Question about the difference between the pseudocode and the implementation

### ISSUE THREAD

**Issue by RachelXu7** [IST-DASLab/gptq#27]
<img width="462" alt="image" src="https://github.com/IST-DASLab/gptq/assets/28942475/d0749136-0850-4386-92d0-96c749abcb08">
<img width="407" alt="image" src="https://github.com/IST-DASLab/gptq/assets/28942475/fcce5fe1-6a3d-425c-b515-b9a9fee0ef78">
The Hessian inverse information in your pseudocode is computed by cholesky of H's inverse. In code, you use the cholesky first and then cholesky inverse and then cholesky again. 
I am not sure the reason of the difference.
And is the cholesky_inverse kernel necessary here？Can I just compute the H's inverse and then use cholesky?

Thank you so much.

**Comment by efrantar** [comment]
Hi! Since the Hessian is symmetric we can calculate its inverse slightly faster and in a more stable way (while also guaranteeing that the output is symmetric) using `cholesky()` + `cholesky_inverse()` (the latter expects as input a Cholesky decomposition). This means the first two lines are just calculating $H^{-1}$ utilizing that $H$ is symmetric.
