### ISSUE TITLE
Application to GPT-J family

### ISSUE THREAD

**Issue by khadijakarchaoui** [IST-DASLab/gptq#3]
Congratulations on your achievement.

Can you give us some hints and recommandations to adapt the procedure in order to quantify the GPT-J models family ?

**Comment by efrantar** [comment]
Hi,

since the GPT-J models are I think pretty standard Transformers, much like OPT and BLOOM, it should not be too difficult to apply GPTQ to those models as well.

There core algorithm in `gptq.py` is designed to work with linear layers and should thus work for GPT-J as well (assuming that the model implementation also uses `nn.Linear` layers). What will however require changes is the code that applies this algorithm to each layer in turn: `opt_sequential()` and `bloom_sequential()` in the `opt.py` and `bloom.py` files, respectively. In general, I believe this should mainly involve changing layer-names to match those in the GPT-J model definition (there might however be some other model-specific details that require some additional adjustments). I would recommend to compare our OPT and BLOOM implementations (`opt.py` and `bloom.py`) to see what is different between them and hence will probably need some adjustment for GPT-J.

I hope this helps a bit.

Elias

**Comment by liangxiaoyun** [comment]
> 你好，
> 
> 由于 GPT-J 模型是我认为非常标准的变形金刚，很像 OPT 和 BLOOM，因此将 GPTQ 应用于这些模型也应该不会太困难。
> 
> 其中的核心算法`gptq.py`设计用于线性层，因此也适用于 GPT-J（假设模型实现也使用`nn.Linear`层）。然而，需要更改的是依次将此算法应用于每一层的代码：分别在`opt_sequential()`和文件`bloom_sequential()`中。总的来说，我认为这应该主要涉及更改图层名称以匹配 GPT-J 模型定义中的图层名称（但是可能还有一些其他特定于模型的细节需要一些额外的调整）。我建议比较我们的 OPT 和 BLOOM 实现（和），看看它们之间有什么不同，因此可能需要对 GPT-J 进行一些调整。`opt.py``bloom.py``opt.py``bloom.py`
> 
> 我希望这个能有一点帮助。
> 
> 埃利亚斯



> 你好，我正在将GPTQ应用到GPT-J模型中，出现了点错误，请问nsamples的意义主要是什么？应用到别的模型上时，nsamples应该怎么修改？
